services:
  dmm-overseerr-bridge:
    build: .
    container_name: dmm-overseerr-bridge
    environment:
      - DMM_URL=https://debridmediamanager.com
      - RD_ACCESS_TOKEN=your_access_token
      - RD_REFRESH_TOKEN=your_refresh_token
      - RD_CLIENT_ID=your_client_id
      - RD_CLIENT_SECRET=your_client_secret
      - RD_CAST_TOKEN=your_cast_token
    ports:
      - "3000:3000"
    restart: unless-stopped
